# Generated by Django 5.2.4 on 2025-07-20 15:14

import airport.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0002_remove_airplane_name_airplane_last_inspection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="airplane",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=airport.models.airplane_image
            ),
        ),
    ]
