# Generated by Django 5.2.4 on 2025-07-27 15:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_airplane_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="airplane",
            options={"verbose_name": "Airplane", "verbose_name_plural": "Airplanes"},
        ),
        migrations.AlterModelOptions(
            name="airplanetype",
            options={
                "verbose_name": "Airplane Type",
                "verbose_name_plural": "Airplane Types",
            },
        ),
        migrations.AlterModelOptions(
            name="airport",
            options={"verbose_name": "Airport", "verbose_name_plural": "Airports"},
        ),
        migrations.AlterModelOptions(
            name="crew",
            options={"verbose_name": "Crew", "verbose_name_plural": "Crew"},
        ),
        migrations.AlterModelOptions(
            name="flight",
            options={
                "ordering": ("departure_time", "arrival_time"),
                "verbose_name": "Flight",
                "verbose_name_plural": "Flights",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order", "verbose_name_plural": "Orders"},
        ),
        migrations.AlterModelOptions(
            name="route",
            options={"verbose_name": "Route", "verbose_name_plural": "Routes"},
        ),
        migrations.AlterModelOptions(
            name="ticket",
            options={"verbose_name": "Ticket", "verbose_name_plural": "Tickets"},
        ),
        migrations.AddField(
            model_name="crew",
            name="license_expiration",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2025, 7, 27, 15, 10, 1, 266329, tzinfo=datetime.timezone.utc
                )
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="crew",
            name="license_number",
            field=models.CharField(default=123, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="route",
            name="stops",
            field=models.ManyToManyField(related_name="stops", to="airport.airport"),
        ),
        migrations.AddField(
            model_name="ticket",
            name="price",
            field=models.DecimalField(decimal_places=2, default=50, max_digits=10),
            preserve_default=False,
        ),
    ]
