# Generated by Django 5.2.4 on 2025-07-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0004_alter_airplane_options_alter_airplanetype_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="total_price",
        ),
        migrations.AlterField(
            model_name="route",
            name="distance",
            field=models.IntegerField(help_text="Distance in kilometers"),
        ),
        migrations.AlterField(
            model_name="route",
            name="stops",
            field=models.ManyToManyField(
                blank=True, related_name="stops", to="airport.airport"
            ),
        ),
    ]
