# Generated by Django 5.2.4 on 2025-07-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0005_remove_order_total_price_alter_route_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "flight"), name="unique_ticket_seat_and_flight"
            ),
        ),
    ]
