# Generated by Django 5.2.4 on 2025-07-31 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0006_order_status_ticket_unique_ticket_seat_and_flight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("CANCELLED", "Cancelled"), ("PAID", "Paid")],
                default="PAID",
                max_length=10,
            ),
        ),
    ]
