# Generated by Django 5.2.4 on 2025-07-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_transaction"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="transaction",
            options={
                "ordering": ["-date"],
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
            },
        ),
    ]
